[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/hoopiq-api-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/players"
healthcheckTimeout = 300
restartPolicyType = "on_failure"