spring.application.name=hoopiq-api

# -------------------------
# DATABASE CONNECTION
# -------------------------

# JDBC URL for your local PostgreSQL database
spring.datasource.url=jdbc:postgresql://localhost:5432/nba_player_insight

# PostgreSQL username
spring.datasource.username=${DB_USER}

# PostgreSQL password
spring.datasource.password=${DB_PASSWORD}

# PostgreSQL JDBC driver
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------
# JPA / HIBERNATE SETTINGS
# -------------------------

# Do not let Hibernate create or modify tables automatically
spring.jpa.hibernate.ddl-auto=none

# Print SQL queries in the console
spring.jpa.show-sql=true

# Format printed SQL so it is easier to read
spring.jpa.properties.hibernate.format_sql=true

# Removes the warning 
spring.jpa.open-in-view=false